name: docs
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  docs:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v3

    # tt tools
    - name: checkout tt tools repo
      uses: actions/checkout@v3
      with:
        repository: tinytapeout/tt-support-tools
        path: tt
        ref: tt03

    # for debugging, show all the files
    - name: show files
      run: find .

    # need python
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r tt/requirements.txt

    # check docs
    - name: build pdf
      run: ./tt/tt_tool.py --check-docs

    # pandoc deps
    - name: Pandoc deps
      run: | 
        sudo apt-get update -y
        sudo apt-get install -y pandoc texlive-xetex

    # create the pdf
    - name: create pdf
      run: ./tt/tt_tool.py --create-pdf

    # archive the PDF
    - name: Archive PDF
      uses: actions/upload-artifact@v3
      with:
          name: PDF
          path: datasheet.pdf
